/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author EvMit8495
 */
public class First extends javax.swing.JFrame {

    /**
     * Creates new form First
     */
    public First() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgm = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        Desc1 = new javax.swing.JLabel();
        Desc2 = new javax.swing.JLabel();
        inputtext = new javax.swing.JLabel();
        input = new javax.swing.JTextField();
        Submit = new javax.swing.JButton();
        output = new javax.swing.JTextField();
        Separator = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        Help = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bgm.setBackground(new java.awt.Color(255, 255, 255));
        bgm.setForeground(new java.awt.Color(255, 255, 255));

        Title.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 204, 0));
        Title.setText("Fibonacci Numbers");

        Desc1.setFont(new java.awt.Font("Stencil Std", 1, 11)); // NOI18N
        Desc1.setText("The first nine fibonacci numbers are listed as");

        Desc2.setFont(new java.awt.Font("Stencil", 0, 11)); // NOI18N
        Desc2.setText("follows: 1, 1, 2, 3, 5, 8, 13, 21, 34");

        inputtext.setFont(new java.awt.Font("Stencil", 0, 11)); // NOI18N
        inputtext.setText("Enter the fibonacci term that you would like to see:");

        input.setForeground(new java.awt.Color(51, 153, 0));
        input.setText("jTextField1");
        input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputActionPerformed(evt);
            }
        });

        Submit.setBackground(new java.awt.Color(0, 0, 0));
        Submit.setForeground(new java.awt.Color(255, 204, 0));
        Submit.setText("Find the Fibonacci Number:");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        output.setForeground(new java.awt.Color(51, 153, 0));
        output.setText("jTextField2");

        javax.swing.GroupLayout bgmLayout = new javax.swing.GroupLayout(bgm);
        bgm.setLayout(bgmLayout);
        bgmLayout.setHorizontalGroup(
            bgmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Separator)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgmLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(bgmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Submit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(output))
                .addGap(123, 123, 123))
            .addGroup(bgmLayout.createSequentialGroup()
                .addGroup(bgmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgmLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(Title))
                    .addGroup(bgmLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(bgmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgmLayout.createSequentialGroup()
                                .addComponent(inputtext)
                                .addGap(18, 18, 18)
                                .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgmLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(Desc1))
                            .addGroup(bgmLayout.createSequentialGroup()
                                .addComponent(Desc2)
                                .addGap(87, 87, 87)))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        bgmLayout.setVerticalGroup(
            bgmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgmLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(Title)
                .addGap(18, 18, 18)
                .addComponent(Desc1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Desc2)
                .addGap(18, 18, 18)
                .addGroup(bgmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputtext)
                    .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Submit)
                .addGap(18, 18, 18)
                .addComponent(output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        File.setText("File");
        jMenuBar1.add(File);

        Help.setText("Help");
        jMenuBar1.add(Help);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
       
       Double n, o;
       n = Double.parseDouble(input.getText());
       int num1=0,num2=1,sum;
       int count;
       for(count = 1;count<= n; count++) {
       sum=num1+num2;
       num1=num2;
       num2=sum;
       output.setText("The " + n + " is " +num1);
       }
      
    }//GEN-LAST:event_SubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(First.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(First.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(First.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(First.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new First().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Desc1;
    private javax.swing.JLabel Desc2;
    private javax.swing.JMenu File;
    private javax.swing.JMenu Help;
    private javax.swing.JSeparator Separator;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel bgm;
    private javax.swing.JTextField input;
    private javax.swing.JLabel inputtext;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField output;
    // End of variables declaration//GEN-END:variables
}
